### ISSUE TITLE
javascript time format error

### ISSUE THREAD

**Issue by reidmweber** [WMSPanel/paywall-code-samples-wmsauth#1]
Format should be:

```
format("UTC:m/d/yyyy h:MM:ss TT");
```

instead of 

```
format("UTC:m/d/yyyy h/MM/ss TT");
```

https://github.com/WMSPanel/paywall-code-samples-wmsauth/blob/master/javascript/wmsauth-example.js#L135

**Comment by WMSPanel** [comment]
It should work both ways. Did you face any issues when using the second option?

**Comment by reidmweber** [comment]
Sorry. Just saw your comment. Yes, when the time format was h/MM/ss it would fail.

**Comment by WMSPanel** [comment]
Thanks for the confirmation, I've made the fix.
