### ISSUE TITLE
basic-hls-rtmp-obfuscation.php need an update

### ISSUE THREAD

**Issue by ghost** [WMSPanel/paywall-code-samples-wmsauth#3]
Hi,
Your code has been bypass by web scrapers https://github.com/WMSPanel/paywall-code-samples-wmsauth/blob/master/php/basic-hls-rtmp-obfuscation.php.
These guys are scraping streams from my website.
https://github.com/Tempest0580/Temptv/issues/27
https://zynetv.net/ae.html
Can you put an update to fix this issue?
Thanks!

**Comment by WMSPanel** [comment]
Hi,
The code you see there is an example which you can improve yourself with your own business logic. We might update it in future but no ETA yet,
