### ISSUE TITLE
Deny list not working

### ISSUE THREAD

**Issue by eightyfive** [WMSPanel/paywall-code-samples-wmsauth#5]
Hi,

This is what I return from the PPV handler:
```json
{
  "DenyList": {
       "ID": [3]
    }
}
```

But the viewer `3` is not kicked out.

**Comment by WMSPanel** [comment]
Can you please send us more details to https://wmspanel.com/help ?

**Comment by eightyfive** [comment]
It's ok now. I had "Enable mutual authorization" activated, so I needed to send a `Solution` back to the Nimble server:

```php
    protected function getResponseSignature(string $puzzle)
    {
        return base64_encode(md5($puzzle . $this->webhookSecret, true));
    }
```

Response:
```json
{
  "Solution":"1zB7iuiiV+O/hoVa9dO3aQ==",
  "DenyList": {
       "ID": [3]
    }
}
```

**Comment by WMSPanel** [comment]
Thank you for the follow up!
